


try:
    print(x)
except:
    print("Something went wrong")
finally:
    print("the 'try except' is finished")

